#ifndef _languageDef
#define _languageDef

#define SIZE_ID 20

#define SYMBOL_TABLE_ENTRIES 7

#define CONSTRUCT_PROGRAM 0
#define CONSTRUCT_ENTRY 1
#define CONSTRUCT_MODULE 2
#define CONSTRUCT_VARIABLE 3
#define CONSTRUCT_WHICH_ID 4
#define CONSTRUCT_CONSTANT 5
#define CONSTRUCT_STATEMENTS 6
#define CONSTRUCT_DECLARE 7
#define CONSTRUCT_ASSIGN 8
#define CONSTRUCT_IO 9
#define CONSTRUCT_SWITCH 10
#define CONSTRUCT_LOOP 11
#define CONSTRUCT_REUSE_MODULE 12
#define CONSTRUCT_OPERATOR 13

#define TYPE_BOOLEAN 0
#define TYPE_INTEGER 1
#define TYPE_REAL 2
#define TYPE_ARRAY 3
#define TYPE_MODULE 4
#define TYPE_MODULE_DECLARE 5

#define WIDTH_BOOLEAN 1
#define WIDTH_INTEGER 2
#define WIDTH_REAL 4
#define WIDTH_ARRAY 4
#define WIDTH_MODULE 1
#define WIDTH_MODULE_DECLARE 1

// this is corresponding to TYPE_x
const static int WIDTHS[] = {
	WIDTH_BOOLEAN,
	WIDTH_INTEGER,
	WIDTH_REAL,
	WIDTH_ARRAY,
	WIDTH_MODULE,
	WIDTH_MODULE_DECLARE,
};

#endif
